### ISSUE TITLE
Duplicated transport head eviction

### ISSUE THREAD

**Issue by panone** [alephzero/alephzero#128]
In `a0_transport_evict()` there is a local copy of state, which is passed to `a0_transport_remove_head()` in a loop. On every execution `a0_transport_remove_head()` performs a commit, so working and committed pages are swapped. Yet the page passed to `a0_transport_remove_head()` does not change, so half the time it operates on the committed page, which is then being overwritten by the working page. So half the time changes done by `a0_transport_remove_head()` are ignored, and it has to be called again.

Is that intended that way for some reason?

**Comment by lshamis** [comment]
It's been a few years since I last looked at the code, but I think it's right. Maybe more nuanced than it should be.
The first thing is that there is no local copy of the state in `a0_transport_evict()`. The code is
```
a0_transport_state_t* state = a0_transport_working_page(lk);
```
Which points into the transport's buffer, in the header section.
The second thing is that, post-commit, the two pages are identical. The purpose of a commit is to ensure that everything is valid if the program crashes mid-operation and another process wants to use the transport.

After the first `a0_transport_remove_head()`, when a commit is performed, both pages are identical to the original working state. When a second commit is performed, the pointer in `a0_transport_evict()` points to updated state info.

**Comment by panone** [comment]
Sorry for the confusion, but by the "local copy of state" I meant the local pointer to one of the pages. I would expect that after each commit `a0_transport_evict()` would need co call `a0_transport_working_page()` to update the pointer, rather than using the local copy. My understanding that all state manipulations are generally performed on the working page, while the committed page is used to rollback any incomplete state changes. The loop in `a0_transport_evict()` violates this assumption.

Let's say we start with working page A1 and committed page B1.
1. `a0_transport_evict()` stores local reference to A, performs the check, discovers intersection and calls `a0_transport_remove_head(A)`.
2. `a0_transport_remove_head()` updates A1 to A2 and calls `a0_transport_commit()`.
3. `a0_transport_commit()` switches working page to B and copies A2 to B2.
4. Now back in `a0_transport_evict()` another check is made and if there is still an intersection, one more frame has to be evicted. So `a0_transport_remove_head()` is called again, **still getting A as an argument**.
5. `a0_transport_remove_head()` updates A2 to A3 and calls `a0_transport_commit()`.
6. `a0_transport_commit()` switches working page to A and **copies B2 over A3** discarding the update performed by `a0_transport_remove_head()`.
7. Again back to `a0_transport_evict()` and again there is still an intersection, since we are essentially back to step 4 with states A2 and B2. But now page A is working again, so call `a0_transport_remove_head(A)` works as intended.
8. `a0_transport_remove_head()` updates A2 to A4 and calls `a0_transport_commit()`.
9. `a0_transport_commit()` switches working page to B and copies A4 to B4.
10. Rinse and repeat.

**Comment by lshamis** [comment]
Thanks for the careful analysis. I think you might be right. Give me a day or so to re-familiarize myself with the details, make sure there isn't something I'm forgetting, then I'll patch it. If you're feeling up to it, you can submit a PR.

**Comment by panone** [comment]
See patch attached to #129.
